services:
  github-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: clocktopus-runner
    environment:
      RUNNER_URL: ${RUNNER_URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME:-clocktopus-runner}
      RUNNER_LABELS: ${RUNNER_LABELS:-self-hosted,linux,deploy}
      RUNNER_GROUP: ${RUNNER_GROUP:-Default}
      RUNNER_WORKDIR: /runner/_work
      RUNNER_EPHEMERAL: ${RUNNER_EPHEMERAL:-}
    env_file:
      - ${RUNNER_ENV_FILE:-envs/clocktopus.env}
    user: "${RUNNER_UID:-1000}:${RUNNER_GID:-1000}"
    volumes:
      - ./work:/runner/_work
      - ${HOST_APPS_PATH:-/home/artificialcrafts/apps}:/apps
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/artificialcrafts/.ssh:/runner/.ssh:ro
    restart: unless-stopped
